export const COUNTRIES = [
    "España",
    "Danmark",
    "Polska",
    "Belgium",
    "Chile",
    "Česko",
    "Nederland",
    "Schweiz",
    "Srbija",
    "Suomi",
    "Slovensko",
    "USA",
    "Bolivia",
    "Angola",
    "Hayastan",
    "Shqiperia",
    "Argentina",
    "Italia",
    "Lietuva",
    "Brasil",
    "China",
    "Colombia",
    "România",
    "Österreich",
    "Nigeria",
    "India",
    "Eesti",
    "Canada",
    "Andorra",
    "Rossiya",
    "Sakartvelo",
    "Iran",
    "Uganda",
    "Madagasikara",
    "México",
    "Deutschland",
    "Hrvatska",
    "Saint Vincent and the Grenadines",
    "Norge",
    "Ukraina",
    "England",
    "Suriname",
    "Bosna i Hercegovina",
    "El Salvador",
    "Sverige",
    "Uruguay",
    "Sri Lanka",
    "Chinese Taipei",
    "Prateh Kampuchea",
    "Hellas",
    "Scotland",
    "Lubnan",
    "Myanmar",
    "Jamaica",
    "Latvija",
    "Comoros",
    "Dawlat Qatar",
    "Moldova",
    "Malta",
    "South Africa",
    "Portugal",
    "Türkiye",
    "Oman",
    "Côte d'Ivoire",
    "Kenya",
    "Lëtzebuerg",
    "Al Yaman",
    "Trinidad & Tobago",
    "Nicaragua",
    "Cuba",
    "República Dominicana",
    "O'zbekiston",
    "Singapore",
    "Ghana",
    "Israel",
    "Prathet Thai",
    "Mongol Uls",
    "San Marino",
    "France",
    "Bulgaria",
    "Palestine",
    "Botswana",
    "United Arab Emirates",
    "Nippon",
    "Pakistan",
    "Bénin",
    "Saudi Arabia",
    "Ireland",
    "Cameroon",
    "São Tomé e Príncipe",
    "Moçambique",
    "Costa Rica",
    "Curaçao",
    "Guatemala",
    "Belize",
    "Tanzania",
    "Puerto Rico",
    "Belarus",
    "Ísland",
    "Al Kuwayt",
    "RD Congo",
    "Perú",
    "Hong Kong",
    "Slovenija",
    "Oceania",
    "Al Maghrib",
    "Ecuador",
    "Indonesia",
    "Crna Gora",
    "Magyarország",
    "Hanguk",
    "Føroyar",
    "Barbados",
    "Algérie",
    "Northern Ireland",
    "Malaysia",
    "Haiti",
    "Cabo Verde",
    "Azərbaycan",
    "Panama",
    "Cymru",
    "Al Urdun",
    "Dhivehi Raajje",
    "Việt Nam",
    "Al Iraq",
    "Liechtenstein",
    "Zambia",
    "Kyrgyzstan",
    "Senegal",
    "Pilipinas",
    "Bahrain",
    "Severna Makedonija",
    "Paraguay",
    "Burkina Faso",
    "Bangladesh",
    "Nepal",
    "Kazakhstan",
    "Guam",
    "Suriyah",
    "Brunei",
    "Misr",
    "Honduras",
    "Grenada",
    "Venezuela",
    "Ītyōṗṗyā",
    "Cyprus",
    "Guyana",
    "Guinée",
    "Tahiti",
    "Tounes",
    "Bahamas",
    "Rwanda",
    "Guinea Ecuatorial",
    "Saint Kitts and Nevis"
].sort();
